easylist/easylistportuguese

easylistportuguese/easylistportuguese_specific_hide.txt

Hiding 'publicidade' placeholders + labels on r7.com

A: https://www.r7.com/

---

easylistportuguese/easylistportuguese_specific_hide.txt

Hide **bettilt** and **tugaiptv** ads on mrpiracy.top
See previous [commit](https://github.com/easylist/easylistportuguese/commit/1f3531cb22331c2e60790645ec787b6d4280821f) > for some reason filters are no longer in PTlist.

A: mrpiracy.top

---

easylistportuguese/easylistportuguese_specific_block_popup.txt
easylistportuguese/easylistportuguese_specific_hide.txt

@jabonsolo add filter: `||futemax.gratis/imagens/logo2.png$popup` to block redirect popup on **futemax.gratis** + added its domain to filter: futemax.fm,futemax.live##.alertWS in order to hide the popup window itself since it keep coming up whether you click on any content.

A: https://futemax.gratis/

---

easylistportuguese/easylistportuguese_specific_hide.txt

Go to [caras.uol.com.br](https://caras.uol.com.br/) and open any article and will see placeholders on the top and throughout the page. 
Below filters should fix that but please feel free to adjust them accordingly. 
```
caras.uol.com.br##.top-banner
caras.uol.com.br##amp-fx-flying-carpet
```

A: caras.uol.com.br

---

easylistportuguese/easylistportuguese_specific_hide.txt

Filter: `tecmundo.com.br##div[id^="slider-partner"]` to hide overlay ad on [tecmundo.com.br](https://www.tecmundo.com.br/) that show up after closing adblock wall message (you have the option to close it without having to disable ABP). [Sample URL](https://www.tecmundo.com.br/mobilidade-urbana-smart-cities/143794-drone-foguete-usado-morador-irritado-acabar-com-festa-rua.htm?f)

A: tecmundo.com.br

---

easylistportuguese/easylistportuguese_adservers.txt
easylistportuguese/easylistportuguese_specific_block.txt
easylistportuguese/easylistportuguese_specific_hide.txt

Rules to block ads on [noticiasdecoimbra.pt](https://www.noticiasdecoimbra.pt/)
1 - `|noticiasdecoimbra.pt/*/modal/*/modal.min*^$stylesheet,script` blocks popup ad overlay (shows up before the cookie consent message and push notification)
2 - `noticiasdecoimbra.pt##div[id^="mvp-leader-wrap"]` hides the ad on the top (before the website logo)
3 - `||skoiy.xyz^$third-party` block skoiy ads on the article pages - [sample URL](https://www.noticiasdecoimbra.pt/toquio2020-portugal-oitavo-na-final-de-ensino-em-equestre/)
4 - `noticiasdecoimbra.pt##div[class*="cp_id_"]` hide ads on the bottom of the article pages

A: noticiasdecoimbra.pt

---

easylistportuguese/easylistportuguese_adservers_popup.txt

`||glixaing.com^$popup,third-party`
Block redirect popup after clicking on the play button https://thefilmes.tv - [Sample URL](http://thefilmes.tv/filmes/693113-midnight-in-the-switchgrass/)
You have to connect to a BR VPN to be able to reproduce the case.

A:  thefilmes.tv

---

easylistportuguese/easylistportuguese_specific_hide.txt

Adding rule: `milkpoint.com.br##a[class^="lnkbn"]` to hide image ads throughout the page. [Sample URL](https://www.milkpoint.com.br/noticias-e-mercado/giro-noticias/nielsen-mulheres-sao-responsaveis-pelas-compras-em-96-dos-lares-213129/)

A: milkpoint.com.br

---

easylistportuguese/easylistportuguese_specific_block_popup.txt

Add `||topflix.vc/images/logo1.png$popup` to block redirect popup on [topflix.vc](https://topflix.vc/filmes/assistir-online-dupla-explosiva-2-e-a-primeira-dama-do-crime/)
Steps to reproduce: When you click on the first option of "Players Disponiveis"  it opens a new popup with https://topflix.vc/images/logo1.png and it redirects to: https://thaveksi.net/4401564.html?q  (for example)

A: topflix.vc

---

easylistportuguese/easylistportuguese_specific_hide.txt

Adds rule: `fogaonet.com##div[class*="fnad-block"]` to hide placeholders on [fogaonet.com](https://www.fogaonet.com/) including [subpages](https://www.fogaonet.com/noticias-do-botafogo/entusiasmado-ceo-botafogo-nota-rafael-havera-reuniao-segunda/)
Below rules from EL seem not enough to hide that
```
##.pp-box-adunit 
##.pp-adunit
```

A: fogaonet.com

---

easylistportuguese/easylistportuguese_specific_hide.txt

Suggestion to replace `netvasco.com.br##.bannervertical` with `netvasco.com.br##a[href^="https://bit.ly/Netvasco-Banner-"]`
since **##.bannervertical** also hides selfpromo that links to their [webshop](https://www.vascoboutique.com.br/).

M: netvasco.com.br

---

easylistportuguese/easylistportuguese_specific_hide.txt

Filter to hide sticky ad on [vagalume.com.br](https://www.vagalume.com.br/) it also happens on subpages
`vagalume.com.br###cazamba_vagalume_passback_container`

A: vagalume.com.br

---

easylistportuguese/easylistportuguese_specific_hide.txt

Hiding filter for [betnabola](https://betnabola.com.br/).
Filter: `betnabola.com.br##section[id^="bouplay_wp_"]`

A: betnabola.com.br

---

easylistportuguese/easylistportuguese_specific_hide.txt

Specific Hiding filter for [Blog.tudogostoso](https://blog.tudogostoso.com.br/)
Header filter : `blog.tudogostoso.com.br##div[data-iab-tag^="content_header_"]`
to hide side placeholders : `blog.tudogostoso.com.br##div[class^="showcase-box arroba"]`

A: blog.tudogostoso.com.br

---

easylistportuguese/easylistportuguese_allowlist_popup.txt

Adding exception to PTlist regarding filters blocking part of the content on below bet websites
```
@@||bet365.com^*affiliate=$popup
@@||refpa.top^$popup
```
EL filters: `||bet365.com^*affiliate=$popup` and `||refpa.top^$popup` prevent bet365 and 1Xbet popups links from opening on:  https://www.academiadasapostasbrasil.com/ 
including subpages: https://www.academiadasapostasbrasil.com/promotions/reviews 
General examples of webpages blocking the popups: 
www.academiadasapostasbrasil.com
https://www.sites-de-apostas.net
www.apostasesportivas24.net
https://www.futebolnaveia.com.br
https://footballpredictions.net/pt
We also noticed that we have a lot of webpages blocking the popups on the Spanish EL, should we also add this exceptions in there ? 
Thank you in advance.

A: allowing bet365 and 1xbet popups

---

easylistportuguese/easylistportuguese_specific_hide.txt

Filter for hiding placeholders at [areah.com.br](https://www.areah.com.br/default.aspx)
Filters were created after an opened issue in EL ES, the webpage is in PT so i'm adding the filters in here. 
https://github.com/easylist/easylistspanish/issues/177
Filters: 
Banner_top : `areah.com.br###banner_top`
Banner_footer and Banner_footer_side : `areah.com.br##div[class^="banner_footer"]`
Placeholder at the bottom of the page: `areah.com.br##div[id^="div-ad-"]`

A: areah.com.br

---

easylistportuguese_adult/adult_adservers.txt

Adserver blocking filter for [belosexo](https://www.belosexo.com/) [NSFW]. 
As I do not have permissions to close the issue i'm referring the same in here: #https://github.com/easylist/easylistportuguese/issues/71 , you can also check the comments provided at the issue, i've added the proposed filter : `||fireadsone.com^$third-party`
All the screenshots and comments are inside the reference.

A: belosexo.com [NSFW]

---

easylistportuguese_adult/adult_specific_hide.txt

Filters for [naoconto](https://www.naoconto.com/) [NSFW]. 
The request was made via the issue #https://github.com/easylist/easylistportuguese/issues/75 , The best way i've found to avoid the ads were via hiding filters, as we had 2 ahref's as parents and a video and image as child's. For that reason i've chose the filters bellow: 
```
naoconto.com##a[href^="https://www.vivalocal.com"]
naoconto.com##a[href^="https://www.camerahot.com"]
```
PS: All the info and screenshots are inside the issue referred above.

A: naoconto.com [NSFW]

---

easylistportuguese/easylistportuguese_general_block.txt
easylistportuguese_adult/adult_specific_hide.txt

Filters for [mulheresafoder](https://www.mulheresafoder.com/) [NSFW]. 
An issue was opened for this specific webpage #https://github.com/easylist/easylistportuguese/issues/80 
While creating the filters i've found another ad in the left side (Together with the other videos).
My proposal is: 
General blocking filter : `||bloco.top$script,image,third-party` (It can be also in non-adult webpages)
Adult specific hiding filter for the placeholders : 
```
mulheresafoder.com###aumento
mulheresafoder.com###sexdate
```
All the data and screenshots for this PR are inside the Issue mentioned above.

A: mulheresafoder.com [NSFW]

---

easylistportuguese_adult/adult_specific_hide.txt

Filter for [novinhasdozapzap](https://novinhasdozapzap.com/) requested via Issue #https://github.com/easylist/easylistportuguese/issues/70
I've tried to block the images (Gifs), but there are other 2 or 3 that are part of the content, another thing is as reported on the issue there is a part called parceiros (partners), on this way i believe it's also part of the webpage. For that reason i decided to go for a really specific hiding filter: `novinhasdozapzap.com###text-59`
All the info and Screenshots are inside the Issue mentioned above.

A: novinhasdozapzap.com [NSFW]

---

easylistportuguese_adult/adult_specific_block.txt

Filters for blocking scripts responsible for emerging popups and ads in all the pages at [manhwa18](https://manhwa18.cc/) 
Proposed blocking filters: 
Popups: `||rowensalmner.com^$script,third-party`
Exoclick ads: `||manhwa18.cc/bmoa^$script`
Screenshots:

A: manhwa18.cc [NSFW]

---

easylistportuguese/easylistportuguese_general_block.txt

Filters for blocking script related to bet ads at [multicanais](https://multicanais.tv/assistir-flamengo-x-barcelona-equ-ao-vivo-online-hd-22-09-2021/)
Proposed filter: `||cdnstatic.cyber.bet$script,third-party`
Screenshot:

A: multicanais.tv

---

easylistportuguese/easylistportuguese_specific_block.txt
easylistportuguese/easylistportuguese_specific_hide.txt

Filters for blocking images path related to ads all over the pages at [reportermt](https://www.reportermt.com.br/)
Proposed filter: `||reportermt.nyc3.digitaloceanspaces.com/*/original$image`
Screenshots:

A: reportermt.com.br

---

easylistportuguese/easylistportuguese_adservers_popup.txt

Filter for blocking adserver popup at [vizer.tv](https://vizer.tv/filme/online/a-familia-mitchell-e-a-revolta-das-maquinas)
Proposed filter: `||ownerswifeimprove.com^$popup,third-party`
Screenshot and how to reproduce : 
click in "assistir", then select "original" and then the first proxy (mixdrop), after that click play till the popup page will appear.

A: vizer.tv

---

easylistportuguese/easylistportuguese_specific_hide.txt

Added domain: **abril.com.br** to an existing rule to hide placeholders on below pages:
- I was able to open [above article](https://saude.abril.com.br/coluna/com-a-palavra/sindrome-de-rokitansky/ ) page on Chrome without getting a paywall. I've seen Outbrain ads at the bottom of the page, in case you can reproduce it, rule: `||outbrain.com^$domain=abril.com.br` should block it.

A: abril.com.br

---

easylistportuguese/easylistportuguese_adservers.txt
easylistportuguese/easylistportuguese_specific_block_popup.txt

Sample URL: https://topflix.fm/filmes/assistir-online-homem-aranha-sem-volta-para-casa-online/
In case the website freezes with dev tools: **view-source:https://topflix.fm/filmes/assistir-online-homem-aranha-sem-volta-para-casa-online/**
[topflix.vc](http://topflix.vc) and [topflix.tv](http://topflix.tv/) are now [topflix.fm](http://topflix.fm/)

A: https://topflix.fm

---

easylistportuguese/easylistportuguese_specific_hide.txt

Hide ad placeholders (top and sidebar) and banner ad (bottom) at https://mangalivre.net/ler/one-piece/online/371782/1044#/!page0
`mangalivre.net##.vignette-content` is not enough to hide the Amazon ads so also adding `mangalivre.net##[amazon-offers-list]`

A: https://mangalivre.net/

---

easylistportuguese/easylistportuguese_specific_hide.txt

Hide ad placeholder at https://yayanimes.net/shingeki-no-kyojin-the-final-season-parte-2-episodio-12/
Ads are being blocked by EL rule:` ||a-ads.com^$third-party` but placeholder remained.
**ABP on**
**ABP off**

A: https://yayanimes.net/

---

easylistportuguese/easylistportuguese_specific_hide.txt

Hide ad popup at  https://xpanimes.com/
Suggested filter: `xpanimes.com##.container > div[style*="z-index:"]`
Adding only `xpanimes.com##.container` would also hides the video frame when you select a title. 
[Sampel URL](https://www.xpanimes.com/play/centraldc.php/?v=&t=&d=&key=&f=&w=&w2=&z=&dc=&cr=https://fy.v.vrv.co/evs3/861ba8dcf8a3c269f34b617aa8be5131/assets/861ba8dcf8a3c269f34b617aa8be5131_4433302.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy84NjFiYThkY2Y4YTNjMjY5ZjM0YjYxN2FhOGJlNTEzMS9hc3NldHMvODYxYmE4ZGNmOGEzYzI2OWYzNGI2MTdhYThiZTUxMzFfNDQzMzMwMi5tcDQvY2xpcEZyb20vMDAwMC9jbGlwVG8vMTIwMDAwL2luZGV4Lm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDk1MTQ2MzF9fX1dfQ__&Signature=Bq96HBlH9fv1eEBkDpXYw3QIo9N6Jk-tSCDh2C~bAwN5 …

A: https://xpanimes.com/

---

easylistportuguese/easylistportuguese_specific_hide.txt

Hide sticky bottom placeholder at https://www.tvpop.com.br/82126/globo-recusou-programa-de-drags-apresentado-por-xuxa-e-ivete-sangalo/
Screenshot:

A: https://www.tvpop.com.br/
