easylist/easylistportuguese

easylistportuguese/easylistportuguese_adservers.txt
=> A: block only ads from Lomadee

easylistportuguese/easylistportuguese_specific_hide.txt
https://forums.lanik.us/viewtopic.php?p=146082#p146082
=> A: https://www.nerdprofessor.com.br/

easylistportuguese/easylistportuguese_specific_hide.txt
Hides empty placeholders throughout pages on letras.mus.br
=> A: letras.mus.br

easylistportuguese/easylistportuguese_allowlist_general_hide.txt
FDA-2233 - allow display video on funimation.com/pt-br
`funimation.com#@#.pub_300x250`
=> A: funimation.com/pt-br

easylistportuguese/easylistportuguese_specific_block.txt
A: https://www.notebookcheck.info/
=> A: https://www.notebookcheck.info/

easylistportuguese/easylistportuguese_specific_hide.txt
Large unblocked blank space on `https://onlineradiobr.com/`
=> A: https://onlineradiobr.com/

easylistportuguese/easylistportuguese_specific_hide.txt
Unblocked space on top of page.
=> A: https://www.astrologiaenlinea.com/pt/Index.asp

easylistportuguese/easylistportuguese_specific_hide.txt
Unblocked empty spaces in `https://www.europa-agricola.pt/tractores-agricolas-usados/7-123/anuncios-tractores-agricolas.html`
=> A: https://www.europa-agricola.pt/tractores-agricolas-usados/7-123/anuncios-tractores-agricolas.html

easylistportuguese/easylistportuguese_specific_hide.txt
Hide placeholders throughout the page on  [brasil247.com](https://www.brasil247.com/) - Ads labeled as 'PUBLICIDADE' (not AA)
`brasil247.com##.adBackground`
=> A: brasil247.com

easylistportuguese/easylistportuguese_adservers.txt, easylistportuguese/easylistportuguese_adservers_popup.txt, easylistportuguese/easylistportuguese_specific_block.txt, easylistportuguese/easylistportuguese_specific_hide.txt
Filter: `||toldmeflex.com^$popup,third-party` to block redirect popup on [mrpiracy.top](https://ww14.mrpiracy.top/); popup comes up after clicking one of the titles.
=> A: ww14.mrpiracy.top

easylistportuguese/easylistportuguese_specific_hide.txt
Adding `publishnews.com.br##div[class^="pn-anuncio"]` to hide ads (mostly animated) on [publishnews.com.br](https://www.publishnews.com.br/)
[Sample URL1](https://www.publishnews.com.br/materias/2021/08/02/apanhadao-tributar-livros-revela-a-estreita-mentalidade-dos-que-o-propoem-avalia-ex-secretario-da-receita)
[Sample URL2](https://www.publishnews.com.br/newsletters/3680)
=> A: publishnews.com.br

easylistportuguese/easylistportuguese_adservers.txt, easylistportuguese/easylistportuguese_adservers_popup.txt, easylistportuguese/easylistportuguese_specific_block_popup.txt
[Sample URL1](https://futebolplayhd.com/assistir-palmeiras-x-sao-paulo-ao-vivo-gratis-hd-17-08-2021/) 
`||futebolplayhd.com/imagens/logo.png$popup` for any option you click on right after you open the page.
`||doaseeph.com^$popup,third-party` for server _Opção 9_ (it didn't work for me with $third-party only)
Redirects for server _Opção 11_ 
```
||azcdn107.net^$third-party - ask to download a file (tested using US and BR VPN)
||ihogaetw.com^$third-party  
||sdxqusoze.com^$third-party
||qjcdnpv.com^$third-party
```
=> A: futebolplayhd.com

easylistportuguese/easylistportuguese_general_block.txt
General Blocking filter for [netfla](https://netfla.com.br/)
`||solution.coupons^$script`
=> A: https://netfla.com.br/

easylistportuguese/easylistportuguese_specific_hide.txt
Hiding filter for [tudogostoso](https://www.tudogostoso.com.br/)
Filters for the placeholders bellow: 
`tudogostoso.com.br##div[class*=“tgads-center”]`
`tudogostoso.com.br##div[class^=“tgad-top”]`
I didn;t wanna hide classses: featured-menu (top) and full-width-content (bottom) because they look part of the content that’s why I added only those filters^
=> A: tudogostoso.com.br

easylistportuguese/easylistportuguese_specific_hide.txt
Filter for hiding the fields with "Publicidade" (ads) on the webpage [futebolbahiano](https://futebolbahiano.org/)
Hiding filter: `futebolbahiano.org##[id^="custom_html-2"]`
Screenshot:
=> A: futebolbahiano.org

easylistportuguese/easylistportuguese_specific_hide.txt
Filter for [futebolbrasil](https://futebolbrasil.online/index)
Hiding filter for those 2 ads on the right side: `futebolbrasil.online##.padd20`
Screenshot:
=> A: futebolbrasil.online

easylistportuguese/easylistportuguese_specific_block.txt
Filter to block iframe ad at the comments of the page [mangalivre-comments](https://mangalivre.net/ler/ookami-kun-wa-hayakawa-san-ni-katenai/online/329694/capitulo-10-5#comments)
Blocking filter: `||static.mangalivre.net$subdocument`
Screenshot:
=> A: mangalivre.net

easylistportuguese/easylistportuguese_specific_block.txt, easylistportuguese/easylistportuguese_specific_hide.txt
Filters to hide ads on [socdgratis](https://www.socdsgratis.top/)
Filter for "Por um site melhor"popup: `socdsgratis.top###cloudbanner`
Filter for 1xbet popups (both with classes starting with "flutua"):  `socdsgratis.top##div[class^="flutua"]`
Filter for a grey layer that appears even if we block the first banner: `socdsgratis.top###modal`
=> A: socdsgratis.top

easylistportuguese/easylistportuguese_specific_block.txt
Block ExitLag images on the right and left side on [mmorpgbr.com.br](http://mmorpgbr.com.br/diminuir-lag-cs-go/)
Although they seem self-promo, they are a bit invasive, different from the ones within the article.
`||mmorpgbr.com.br/wp-content/uploads/2021/05/Banner-Skin_$image`
=> A: mmorpgbr.com.br

easylistportuguese/easylistportuguese_general_block.txt
Filter for blocking the requests to another page for the following website: [animepahe](https://animepahe.com/play/384752a5-55bc-af54-257b-3f32f49599c1/fc4d5921f3aa1c8d6458d726cf2941b886ba24f989d90b61eefed09246af495c)
Proposed filter: `||gorillabrightenarms.com$script,third-party`
Situation reproduced: [screen record](https://vimeo.com/616946379/69361a1d14)
=> A: animepahe.com

easylistportuguese/easylistportuguese_specific_hide.txt
Filterfor hiding image ad at [animesgratisbr](https://www.animesgratisbr.biz/video/118613/)
Proposed hiding filter: `animesgratisbr.biz##img[title^="Assistir Hentai"]`
Screenshot: ![image](https://user-images.githubusercontent.com/65717387/135093545-b6d27833-623f-410d-b9f4-db05b490b81f.png)
=> A: animesgratisbr.biz

easylistportuguese/easylistportuguese_specific_hide.txt
Filter for hiding intrusive ad at [sofilmeshd](https://sofilmeshd.piracyproxy.info/#)
Proposed filter: `sofilmeshd.piracyproxy.info##[id^="cookieConsent"]`
Screenshot:
=> A: sofilmeshd.piracyproxy.info

easylistportuguese/easylistportuguese_specific_block.txt
Filter for blocking sticky video at all the main page and subdomains at [xpanimes](https://xpanimes.com/)
Proposed filter: `||adlyra.com$subdocument,third-party`
Screenshot:
=> A: xpanimes.com

easylistportuguese/easylistportuguese_specific_block.txt
There's one unblocked square banner on the right hand side of `https://www.conjugacao-de-verbos.com/`.
=> A: https://www.conjugacao-de-verbos.com/

easylistportuguese_adult/adult_specific_block.txt
Filters for blocking redirects after clicking on any header element at [pornhits](http://pornhits.com).
I believe it should go on EL but as it was on the PT top 10k i've done the PR in here for now, if i do need to do this PR in there just let me know. 
Proposed filter: `||www.pornhits.com/magic^$script`
How to reproduce: Open the main page and click at categories for example.
=> A: pornhits.com [NSFW]

easylistportuguese/easylistportuguese_specific_block.txt
Updated filter for the Amazon text ads.
=> M: https://www.notebookcheck.info/

easylistportuguese/easylistportuguese_specific_hide.txt
Hide placeholders at https://www.globo.com/
Closes #155
=> A: https://www.globo.com/

easylistportuguese/easylistportuguese_specific_hide.txt
=> A: https://www.tuasaude.com/

easylistportuguese/easylistportuguese_specific_hide.txt
=> A: Placeholders on uol.com.br

easylistportuguese/easylistportuguese_specific_hide.txt
Hide close icon on image slider and Ad labels throughout the page.
URL: https://www.estrelando.com.br/foto/2022/02/28/estressada-chocolatra-cinefila-veja-cinco-curiosidades-sobre-a-sandy-que-voc%C3%AA-nao-conhecia-203466//foto-1
**Suggested filters:**
`estrelando.com.br###publi-pop`
`estrelando.com.br##.text-anuncio`
=> A: https://www.estrelando.com.br

easylistportuguese/easylistportuguese_specific_hide.txt
=> A: https://revistaquem.globo.com/

easylistportuguese/easylistportuguese_specific_hide.txt
Hide banner at https://www.ofertaspravoce.com/
=> A: https://www.ofertaspravoce.com/

easylistportuguese/easylistportuguese_specific_hide.txt
https://soesporte.com.br/
https://www.naoleveportras.net/
https://ocamera.com.br/
https://ocamera.com.br/elemento-e-preso-em-mossoro-com-uma-pistola-roubada-de-um-policial-de-folga-numa-praia-do-ceara/ 
https://pescariasa.com.br/
https://comidasimples.com.br/curiosidades/o-consumo-excessivo-de-acucar-tem-relacao-com-ansiedade-saiba-mais/ https://fimdalinha.com.br/
=> A: Hide banners

easylistportuguese/easylistportuguese_specific_hide.txt
Hi please review and add this filter to hide the empty space left out from advertising.
Thank you
=> A: `noticiasaominuto.com`

easylistportuguese/easylistportuguese_specific_hide.txt
Hi please go on this [article page](https://portaldeprefeitura.com.br/2023/10/concurso-no-recife-joao-campos-autoriza-certame-para-emlurb-e-urb-confira-detalhes_/) and you will notice there are 2 banners on top of the page and a couple of banners on the right side of the page:
=> A:`portaldeprefeitura.com.br`
